### ISSUE TITLE
1.8.6 - Several warnings exporting to ODT

### ISSUE THREAD

**Issue by andrepetinga** [TECLIB/mreporting#252]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

1.8.6

### Bug description

When I try to export a report to ODT format, I'm getting several warnings if I enable Debug Mode:

**Warnings**: 

![image](https://github.com/user-attachments/assets/bcbd871c-70cf-47ce-9ea1-93f79a3a9c2d)

![image](https://github.com/user-attachments/assets/975b3868-eca1-4f64-82c8-18dc5c8d6d7c)

Regarding this warnings, I guess you just have to update the functions to the new ones.

### Steps To reproduce

1. Enable Debug Mode
2. Open Tools -> More Reporting
3. Choose a report
4. On the Export option, choose ODT
5. Press "Post"

**Comment by andrepetinga** [comment]
...

**Comment by stonebuzz** [comment]
should be fixed with https://github.com/pluginsGLPI/mreporting/pull/279

**Comment by andrepetinga** [comment]
Just apllied the #279 and the warnings are still present.

One thing I forgot to mention: With 1.8.7 version, the warnings are displayed when I open the report, not on the Export option.

And now, with the #279 PR, the only thing that is different are the line numbers of the warnings, that were increased +1.

![Image](https://github.com/user-attachments/assets/9a142d08-657e-4b4c-abf5-7aac910defc6)
